name: Lint

on: push

jobs:
  run-linters:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
